name: pawfectcare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Add additional dependencies below
  provider: ^6.0.0 # If you're managing state
  cached_network_image: ^3.2.1 # For caching images
  flutter_svg: ^1.0.3 # If you're using SVG images
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2 # Firestore for database
  firebase_storage: ^12.3.1
  firebase_analytics: ^11.3.2
  firebase_messaging: ^15.1.2
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bella.png
    - assets/images/furry.png
    - assets/images/news1.png
    - assets/images/roudy.png
    - assets/images/Pawfectcare.png
    - assets/images/google.png



